### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NoFaceGamer06** [DrakeTheDuelist/MAS-Dreams-and-Nightmares#3]
Just installed this submod and:
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/Dreams and Nightmares/DaN-_submod-updater.rpy", line 2, in script
    init -990 python:
  File "game/Submods/Dreams and Nightmares/DaN-_submod-updater.rpy", line 7, in <module>
    version="1.0.3"
  File "game/zz_submods.rpy", line 130, in __init__
SubmodError: Name 'MAS-Dreams-and-Nightmares' is invalid.

Any idea?

**Comment by wboorman** [comment]
It's not ready to install yet.  There's a handful of things I'm still trying to work out, and figuring out how to get the submod updater plugin to behave itself is a big one.

**Comment by NoFaceGamer06** [comment]
Whoops i'm sorry, didn't knew that, well once Is ready to be installed i will make sure ti download It and try it
